name: Release
on: [push]

jobs:
  build-and-release:
    if: "contains(github.event.head_commit.message, '[Release] ')"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm install --include=dev

      - name: Build and Package
        run: npm run build
        
      - name: Copy App to Workspace
        run: cp -r out/*/Cheese.app /github/workspace/

      - name: Get changes since last release
        id: changes
        uses: simbo/changes-since-last-release-action@v1

      - name: Release App
        run: |
          title=$(echo "${{ github.event.head_commit.message }}" | sed "s/\[Release\] //g")
          gh release create date+"%Y-%m-%d" /github/workspace/Cheese.app --title "$title" --notes "${{ steps.changes.outputs.log }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
